import { useEffect, useRef, useState } from "react";
import { AgentMark, Button, Pill } from "@/components/ui";
import { PRODUCTS, SUPPLIERS } from "@/lib/mock-data";
import { cn } from "@/lib/utils";

type Msg =
  | { kind: "user"; text: string }
  | { kind: "agent"; text: string }
  | { kind: "sku-match"; sku: string }
  | { kind: "supplier-ambiguity"; term: string };

const QUICK = ["Create a PO", "Show my approvals", "What's blocking PO2664?"];

const STEPS = [
  "Reading your message…",
  "Looking up the product master…",
  "Checking supplier records…",
  "Drafting a reply…",
];

export function AssistantPanel({
  open,
  onClose,
  context,
}: {
  open: boolean;
  onClose: () => void;
  context?: string;
}) {
  const [messages, setMessages] = useState<Msg[]>([
    {
      kind: "agent",
      text: context
        ? `Ask about ${context} — I already have the record open.`
        : "Ask me to raise a PO, chase an approval or explain an exception.",
    },
  ]);
  const [draft, setDraft] = useState("");
  const [thinking, setThinking] = useState<number | null>(null);
  const endRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    endRef.current?.scrollIntoView({ block: "end" });
  }, [messages, thinking]);

  useEffect(() => {
    if (thinking === null) return;
    if (thinking >= STEPS.length) {
      setThinking(null);
      setMessages((m) => [
        ...m,
        { kind: "sku-match", sku: "PKG8060" },
        { kind: "supplier-ambiguity", term: "Harbour" },
        {
          kind: "agent",
          text: "I still need a drop-dead ready date — 3 of 5 mandatory fields captured.",
        },
      ]);
      return;
    }
    const t = setTimeout(() => setThinking((s) => (s === null ? null : s + 1)), 550);
    return () => clearTimeout(t);
  }, [thinking]);

  const send = (text: string) => {
    if (!text.trim()) return;
    setMessages((m) => [...m, { kind: "user", text }]);
    setDraft("");
    setThinking(0);
  };

  return (
    <aside
      className={cn(
        "shrink-0 border-l border-border bg-card transition-all duration-200",
        open ? "w-[360px]" : "w-0 overflow-hidden",
      )}
      aria-label="Assistant panel"
    >
      <div className="flex h-full w-[360px] flex-col">
        <header className="flex items-center justify-between border-b border-border px-4 py-3">
          <div>
            <div className="text-sm font-semibold">Assistant</div>
            <div className="text-xs text-muted-foreground">
              {context ? `Context: ${context}` : "Context: workspace"}
            </div>
          </div>
          <Button variant="ghost" size="sm" onClick={onClose} aria-label="Collapse assistant">
            ✕
          </Button>
        </header>

        <div className="flex-1 space-y-3 overflow-y-auto px-4 py-4">
          {messages.map((m, i) => (
            <MessageBubble key={i} msg={m} />
          ))}
          {thinking !== null ? (
            <div className="rounded-xl bg-accent-soft px-3 py-2 text-xs text-accent">
              <span className="animate-pulse">✦</span> {STEPS[Math.min(thinking, STEPS.length - 1)]}
            </div>
          ) : null}
          <div ref={endRef} />
        </div>

        <div className="border-t border-border px-4 py-3">
          <div className="mb-2 flex flex-wrap gap-1.5">
            {QUICK.map((q) => (
              <button
                key={q}
                onClick={() => send(q)}
                className="rounded-full border border-border px-2.5 py-1 text-xs text-muted-foreground hover:bg-muted hover:text-foreground"
              >
                {q}
              </button>
            ))}
          </div>
          <form
            onSubmit={(e) => {
              e.preventDefault();
              send(draft);
            }}
            className="flex gap-2"
          >
            <input
              value={draft}
              onChange={(e) => setDraft(e.target.value)}
              placeholder="Ask the assistant…"
              className="h-9 flex-1 rounded-full border border-input bg-background px-3 text-sm outline-none focus:border-primary"
            />
            <Button type="submit" variant="primary" size="sm">
              Send
            </Button>
          </form>
        </div>
      </div>
    </aside>
  );
}

function MessageBubble({ msg }: { msg: Msg }) {
  if (msg.kind === "user")
    return (
      <div className="ml-auto max-w-[85%] rounded-xl bg-primary px-3 py-2 text-sm text-primary-foreground">
        {msg.text}
      </div>
    );

  if (msg.kind === "agent")
    return (
      <div className="max-w-[90%] rounded-xl bg-muted px-3 py-2 text-sm">
        <AgentMark why="Generated by the intake agent from your message and the product master." />
        <p className="mt-1.5">{msg.text}</p>
      </div>
    );

  if (msg.kind === "sku-match") {
    const p = PRODUCTS.find((x) => x.sku === msg.sku)!;
    return (
      <div className="rounded-xl border border-accent-soft bg-card p-3 shadow-soft">
        <div className="flex items-center justify-between">
          <span className="num text-sm font-semibold">{p.sku}</span>
          <AgentMark why="Matched from the phrase you used, plus a learned alias." >Suggested</AgentMark>
        </div>
        <p className="mt-1 text-sm">{p.description}</p>
        <dl className="mt-2 grid grid-cols-2 gap-x-3 gap-y-1 text-xs text-muted-foreground">
          <div>Category · {p.category}</div>
          <div>Tier 1 · {p.tier1}</div>
          <div>Tier 2 · {p.tier2}</div>
          <div>Variant · {p.variant}</div>
          <div>Market · {p.market}</div>
          <div>MOQ · {p.moq.toLocaleString("en-GB")}</div>
        </dl>
        <div className="mt-3 flex gap-2">
          <Button size="sm" variant="primary">
            Confirm
          </Button>
          <Button size="sm">Show alternatives</Button>
        </div>
      </div>
    );
  }

  const matches = SUPPLIERS.filter((s) => s.name.includes(msg.term));
  return (
    <div className="rounded-xl border border-warning-soft bg-card p-3 shadow-soft">
      <div className="flex items-center justify-between">
        <span className="text-sm font-semibold">“{msg.term}” matches {matches.length} suppliers</span>
        <Pill tone="attention" icon={false}>
          Choose one
        </Pill>
      </div>
      <ul className="mt-2 space-y-2">
        {matches.map((s) => (
          <li key={s.id} className="flex items-center justify-between gap-2 rounded-lg bg-muted px-2.5 py-2">
            <div>
              <div className="text-sm font-medium">{s.name}</div>
              <div className="num text-xs text-muted-foreground">
                {s.region} · {s.leadTimeDays} d · on-time {s.onTimePct}%
              </div>
            </div>
            <Button size="sm" variant={s.status === "Approved/Active" ? "primary" : "outline"} disabled={s.status !== "Approved/Active"} title={s.status !== "Approved/Active" ? "Supplier is not approved — blocked" : undefined}>
              Select
            </Button>
          </li>
        ))}
      </ul>
    </div>
  );
}
